name: MinecraftServer

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::082113759242:role/github_oidc_role
          aws-region: eu-central-1
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8
      - name: Initialize Terraform
        working-directory: infrastructure
        run: terraform init
      - name: Terraform Apply
        working-directory: infrastructure
        run: terraform apply -auto-approve